# Generated by Django 6.0.4 on 2026-04-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='edit_reason',
            field=models.TextField(blank=True, verbose_name='Lý do chỉnh sửa'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm chỉnh sửa'),
        ),
    ]
