# Generated by Django 6.0.4 on 2026-04-28 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_dailymenu_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên nguyên liệu')),
                ('default_unit', models.CharField(choices=[('g', 'Gram'), ('kg', 'Kg'), ('ml', 'Ml'), ('l', 'Lít'), ('piece', 'Phần')], default='g', max_length=20, verbose_name='Đơn vị mặc định')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nguyên liệu',
                'verbose_name_plural': 'Nguyên liệu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Khẩu phần / người')),
                ('unit', models.CharField(choices=[('g', 'Gram'), ('kg', 'Kg'), ('ml', 'Ml'), ('l', 'Lít'), ('piece', 'Phần')], default='g', max_length=20, verbose_name='Đơn vị')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meals.dish', verbose_name='Món ăn')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient', verbose_name='Nguyên liệu')),
            ],
            options={
                'verbose_name': 'Nguyên liệu món ăn',
                'verbose_name_plural': 'Nguyên liệu món ăn',
                'ordering': ['ingredient__name'],
                'unique_together': {('dish', 'ingredient', 'unit')},
            },
        ),
    ]
