# Generated by Django 6.0.4 on 2026-04-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_ingredient_dishingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='portion_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kg'), ('ml', 'Ml'), ('l', 'Lít'), ('phần', 'Phần'), ('quả', 'Quả')], default='g', max_length=20, verbose_name='Đơn vị'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kg'), ('ml', 'Ml'), ('l', 'Lít'), ('phần', 'Phần'), ('quả', 'Quả')], default='g', max_length=20, verbose_name='Đơn vị'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='default_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kg'), ('ml', 'Ml'), ('l', 'Lít'), ('phần', 'Phần'), ('quả', 'Quả')], default='g', max_length=20, verbose_name='Đơn vị mặc định'),
        ),
    ]
