# Generated by Django 6.0.4 on 2026-04-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_mealregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealRegistration',
        ),
        migrations.DeleteModel(
            name='MealRegistrationSummary',
        ),
    ]
