# Generated by Django 6.0.4 on 2026-05-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_alter_weeklymenudraft_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymenudraft',
            name='status',
            field=models.CharField(choices=[('suggested', 'AI đã gợi ý'), ('applied', 'Đã chọn món (chờ lưu)')], default='suggested', max_length=20),
        ),
    ]
