# Generated by Django 6.0.4 on 2026-05-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_weeklymenudraft_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, help_text='Nội dung hấp dẫn về món (đặc điểm, nguồn gốc, lợi ích...) — hiển thị ở màn hình bếp ăn.', verbose_name='Giới thiệu món ăn'),
        ),
    ]
