# Generated by Django 6.0.4 on 2026-05-31 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_dish_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPrepOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm xác nhận')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận')),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prep_order', to='meals.dailymenu', verbose_name='Thực đơn')),
            ],
            options={
                'verbose_name': 'Đơn nguyên liệu chuẩn bị',
                'verbose_name_plural': 'Đơn nguyên liệu chuẩn bị',
            },
        ),
        migrations.CreateModel(
            name='MenuPrepOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255, verbose_name='Nguyên liệu')),
                ('dish_names', models.CharField(blank=True, max_length=500, verbose_name='Dùng trong món')),
                ('quantity_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Khẩu phần/người')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng khối lượng')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Đơn vị')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meals.menupreporder', verbose_name='Đơn')),
            ],
            options={
                'verbose_name': 'Dòng nguyên liệu chuẩn bị',
                'verbose_name_plural': 'Dòng nguyên liệu chuẩn bị',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
