# Generated by Django 6.0.4 on 2026-04-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Từ ngày')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Đến ngày')),
                ('meal_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá suất ăn')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình giá suất ăn',
                'verbose_name_plural': 'Cấu hình giá suất ăn',
                'ordering': ['-start_date'],
            },
        ),
    ]
