# Generated by Django 6.0.4 on 2026-05-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mealpricechangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNutritionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_kcal', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
