# Generated by Django 6.0.4 on 2026-05-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailynutritionanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('scan_time', models.DateTimeField()),
                ('type', models.CharField(default='bếp ăn', max_length=50)),
                ('status', models.CharField(choices=[('Đã đăng ký', 'Đã đăng ký'), ('Chưa đăng ký', 'Chưa đăng ký')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
