# Generated by Django 6.0.4 on 2026-05-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealpricechangelog',
            name='new_spice_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá gia vị mới'),
        ),
        migrations.AddField(
            model_name='mealpricechangelog',
            name='old_spice_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá gia vị cũ'),
        ),
        migrations.AddField(
            model_name='mealpricesetting',
            name='spice_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá gia vị mỗi suất'),
        ),
    ]
