# Generated by Django 6.0.4 on 2026-05-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mealpricechangelog_new_spice_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(db_index=True, max_length=64, verbose_name='Mã camera')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10, verbose_name='Trạng thái')),
                ('changed_at', models.DateTimeField(db_index=True, verbose_name='Thời điểm chuyển')),
            ],
            options={
                'verbose_name': 'Log trạng thái camera',
                'verbose_name_plural': 'Log trạng thái camera',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionHeartbeat',
            fields=[
                ('camera_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Mã camera')),
                ('last_heartbeat_at', models.DateTimeField(verbose_name='Heartbeat gần nhất')),
                ('last_info', models.JSONField(blank=True, null=True, verbose_name='Thông tin kèm theo')),
            ],
            options={
                'verbose_name': 'Heartbeat camera nhận diện',
                'verbose_name_plural': 'Heartbeat camera nhận diện',
            },
        ),
    ]
