# Generated by Django 6.0.4 on 2026-05-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_camerastatuslog_recognitionheartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=50, verbose_name='Mã nhân viên')),
                ('camera_id', models.CharField(blank=True, max_length=64, verbose_name='Mã camera')),
                ('scan_time', models.DateTimeField(db_index=True, verbose_name='Thời gian quét')),
                ('status', models.CharField(blank=True, max_length=30, verbose_name='Trạng thái')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Độ khớp')),
                ('image', models.ImageField(upload_to='attendance_captures/%Y/%m/%d/', verbose_name='Ảnh chụp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ảnh chụp nhận diện',
                'verbose_name_plural': 'Ảnh chụp nhận diện',
                'ordering': ['-scan_time'],
            },
        ),
    ]
