# Generated by Django 6.0.4 on 2026-06-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_attendancecapture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayGreetingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, verbose_name='Mã nhân viên')),
                ('greeting_date', models.DateField(db_index=True, verbose_name='Ngày chúc mừng')),
                ('shown_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm chiếu')),
            ],
            options={
                'verbose_name': 'Log chúc mừng sinh nhật',
                'verbose_name_plural': 'Log chúc mừng sinh nhật',
                'unique_together': {('employee_code', 'greeting_date')},
            },
        ),
    ]
