# Generated by Django 6.0.4 on 2026-04-24 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypurchase',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm phê duyệt'),
        ),
        migrations.AddField(
            model_name='dailypurchase',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Người phê duyệt'),
        ),
        migrations.AddField(
            model_name='dailypurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã duyệt')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
