# Generated by Django 6.0.4 on 2026-04-28 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_dailypurchase_bill_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypurchase',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='Lý do từ chối'),
        ),
        migrations.AddField(
            model_name='dailypurchase',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm từ chối'),
        ),
        migrations.AddField(
            model_name='dailypurchase',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Người từ chối'),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
