# Generated by Django 6.0.4 on 2026-05-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_dailypurchase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseextraitem',
            options={},
        ),
        migrations.AddField(
            model_name='purchaseextraitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Đơn giá'),
        ),
    ]
