# Generated by Django 6.0.4 on 2026-05-04 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_extrapurchaserequest_extrapurchaserequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypurchase',
            name='extra_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='finance.extrapurchaserequest', verbose_name='Đơn mua bổ sung liên kết'),
        ),
    ]
