# Generated by Django 6.0.4 on 2026-05-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_dailypurchase_extra_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrapurchaserequest',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
