# Generated by Django 6.0.4 on 2026-05-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_extrapurchaserequest_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrapurchaserequest',
            name='code',
        ),
    ]
