# Generated by Django 6.0.4 on 2026-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_extrapurchaserequest_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseextraitem',
            options={'verbose_name': 'Mặt hàng trong hóa đơn', 'verbose_name_plural': 'Mặt hàng trong hóa đơn'},
        ),
        migrations.AddField(
            model_name='purchaseextraitem',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày'),
        ),
    ]
