# Generated by Django 6.0.4 on 2026-05-15 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_purchaseextraitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypurchase',
            name='was_edited_after_approval',
            field=models.BooleanField(default=False, verbose_name='Đã chỉnh sửa sau khi duyệt'),
        ),
        migrations.CreateModel(
            name='PurchaseEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm sửa')),
                ('previous_status', models.CharField(blank=True, max_length=20, verbose_name='Trạng thái trước khi sửa')),
                ('reason', models.TextField(verbose_name='Lý do chỉnh sửa')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người chỉnh sửa')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='finance.dailypurchase', verbose_name='Chi phí')),
            ],
            options={
                'verbose_name': 'Lịch sử chỉnh sửa chi phí',
                'verbose_name_plural': 'Lịch sử chỉnh sửa chi phí',
                'ordering': ['-edited_at'],
            },
        ),
    ]
