# Generated by Django 6.0.4 on 2026-05-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_dailypurchase_was_edited_after_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypurchase',
            name='purchase_type',
            field=models.CharField(choices=[('main', 'Mua thực phẩm'), ('extra', 'Mua gia vị')], default='main', max_length=20, verbose_name='Phân loại'),
        ),
    ]
