# Generated by Django 6.0.4 on 2026-05-29 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_dailypurchase_purchase_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored_date', models.DateField(verbose_name='Ngày lưu tồn')),
                ('ingredient_name', models.CharField(max_length=255, verbose_name='Nguyên liệu')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Khối lượng tồn')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Đơn vị')),
                ('source', models.CharField(choices=[('manual', 'Nhập tay'), ('invoice', 'Từ hóa đơn')], default='manual', max_length=20, verbose_name='Nguồn nhập')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người nhập')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
                'ordering': ['-stored_date', 'ingredient_name'],
            },
        ),
    ]
