# Generated by Django 6.0.4 on 2026-05-29 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_inventoryentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryentry',
            options={'ordering': ['ingredient_name'], 'verbose_name': 'Tồn kho', 'verbose_name_plural': 'Tồn kho'},
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', 'Nhập kho'), ('export', 'Xuất kho')], max_length=10, verbose_name='Thao tác')),
                ('action_date', models.DateField(verbose_name='Ngày')),
                ('ingredient_name', models.CharField(max_length=255, verbose_name='Nguyên liệu')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Khối lượng')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Đơn vị')),
                ('source', models.CharField(blank=True, max_length=20, verbose_name='Nguồn')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Lịch sử kho',
                'verbose_name_plural': 'Lịch sử kho',
                'ordering': ['-created_at'],
            },
        ),
    ]
