# Generated by Django 6.0.4 on 2026-04-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phòng'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã nhân viên'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Họ và tên'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chức danh'),
        ),
    ]
