# Generated by Django 6.0.4 on 2026-04-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_avatar_mealregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealRegistration',
        ),
    ]
