# Generated by Django 6.0.4 on 2026-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
