# Generated by Django 6.0.4 on 2026-07-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_by_password',
            field=models.BooleanField(default=False, verbose_name='Đăng nhập bằng mật khẩu (nhân viên thuê ngoài)'),
        ),
    ]
