# Generated by Django 6.0.4 on 2026-04-21 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên món')),
                ('dish_type', models.CharField(choices=[('main', 'Món chính'), ('side', 'Món phụ'), ('soup', 'Món canh'), ('dessert', 'Món tráng miệng')], max_length=20, verbose_name='Loại món')),
                ('portion_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Khẩu phần / người')),
                ('portion_unit', models.CharField(choices=[('g', 'Gram'), ('kg', 'Kg'), ('ml', 'Ml'), ('l', 'Lít'), ('piece', 'Phần')], default='g', max_length=20, verbose_name='Đơn vị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Món ăn',
                'verbose_name_plural': 'Món ăn',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealRegistrationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Ngày')),
                ('registered_count', models.PositiveIntegerField(default=0, verbose_name='Số người đăng ký')),
            ],
            options={
                'verbose_name': 'Tổng đăng ký ăn',
                'verbose_name_plural': 'Tổng đăng ký ăn',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Ngày áp dụng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('approved', 'Đã duyệt')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Menu ngày',
                'verbose_name_plural': 'Menu ngày',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DailyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meals.dailymenu', verbose_name='Menu ngày')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.dish', verbose_name='Món ăn')),
            ],
            options={
                'verbose_name': 'Chi tiết menu ngày',
                'verbose_name_plural': 'Chi tiết menu ngày',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('daily_menu', 'dish')},
            },
        ),
    ]
