# Generated by Django 6.0.4 on 2026-04-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_dailymenu_edit_reason_dailymenu_last_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã duyệt')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
