# Generated by Django 6.0.4 on 2026-04-28 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_dailymenu_reject_reason_dailymenu_rejected_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='MenuRejectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày thực đơn')),
                ('reject_reason', models.TextField(verbose_name='Lý do từ chối')),
                ('rejected_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm từ chối')),
                ('created_by_username', models.CharField(blank=True, max_length=150, verbose_name='Mã người tạo')),
                ('created_by_full_name', models.CharField(blank=True, max_length=255, verbose_name='Tên người tạo')),
                ('menu_snapshot', models.TextField(blank=True, verbose_name='Snapshot món ăn')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reject_logs', to='meals.dailymenu', verbose_name='Thực đơn')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_reject_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người từ chối')),
            ],
            options={
                'verbose_name': 'Lịch sử từ chối thực đơn',
                'verbose_name_plural': 'Lịch sử từ chối thực đơn',
                'ordering': ['-rejected_at'],
            },
        ),
    ]
