# Generated by Django 6.0.4 on 2026-04-28 13:06

import meals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_dailymenu_status_menurejectlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=meals.models.upload_dish_image, verbose_name='Ảnh món ăn'),
        ),
    ]
