# Generated by Django 6.0.4 on 2026-04-28 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_dish_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymenu',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='dailymenuitem',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='dishingredient',
            options={'ordering': ['ingredient__name']},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mealregistrationsummary',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='menurejectlog',
            options={'ordering': ['-rejected_at']},
        ),
        migrations.AddField(
            model_name='dish',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dishes', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AddField(
            model_name='dish',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='Lý do từ chối'),
        ),
        migrations.AddField(
            model_name='dish',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_dishes', to=settings.AUTH_USER_MODEL, verbose_name='Người từ chối'),
        ),
        migrations.AddField(
            model_name='dish',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='edit_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_menus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailymenuitem',
            name='daily_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meals.dailymenu'),
        ),
        migrations.AlterField(
            model_name='dailymenuitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.dish'),
        ),
        migrations.AlterField(
            model_name='dailymenuitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meals.dish'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='quantity_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kg'), ('ml', 'Ml'), ('l', 'Lít'), ('phần', 'Phần'), ('quả', 'Quả')], default='g', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='default_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kg'), ('ml', 'Ml'), ('l', 'Lít'), ('phần', 'Phần'), ('quả', 'Quả')], default='g', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='menurejectlog',
            name='created_by_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='menurejectlog',
            name='created_by_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='menurejectlog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='menurejectlog',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reject_logs', to='meals.dailymenu'),
        ),
        migrations.AlterField(
            model_name='menurejectlog',
            name='menu_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='menurejectlog',
            name='reject_reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menurejectlog',
            name='rejected_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menurejectlog',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_reject_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DishRejectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=255)),
                ('dish_type', models.CharField(blank=True, max_length=20)),
                ('reject_reason', models.TextField()),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('created_by_full_name', models.CharField(blank=True, max_length=255)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reject_logs', to='meals.dish', verbose_name='Món ăn')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_reject_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rejected_at'],
            },
        ),
    ]
