# Generated by Django 6.0.4 on 2026-04-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_alter_dailymenu_options_alter_dailymenuitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('meal_name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-date', 'employee_code'],
                'unique_together': {('employee_code', 'date', 'meal_name')},
            },
        ),
    ]
