# Generated by Django 6.0.4 on 2026-04-21 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Ngày')),
                ('actual_cost', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Chi phí mua thực tế')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người nhập')),
            ],
            options={
                'verbose_name': 'Chi phí mua hàng ngày',
                'verbose_name_plural': 'Chi phí mua hàng ngày',
                'ordering': ['-date'],
            },
        ),
    ]
