# Generated by Django 6.0.4 on 2026-04-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_dailypurchase_approved_at_dailypurchase_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypurchase',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to='purchase_bills/', verbose_name='Ảnh bill'),
        ),
    ]
