# Generated by Django 6.0.4 on 2026-04-28 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_dailypurchase_reject_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRejectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày chi phí')),
                ('actual_cost', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Chi phí')),
                ('reject_reason', models.TextField(verbose_name='Lý do từ chối')),
                ('rejected_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm từ chối')),
                ('created_by_username', models.CharField(blank=True, max_length=150, verbose_name='Mã người nhập')),
                ('created_by_full_name', models.CharField(blank=True, max_length=255, verbose_name='Tên người nhập')),
                ('note_snapshot', models.TextField(blank=True, verbose_name='Ghi chú tại thời điểm từ chối')),
                ('bill_image_snapshot', models.ImageField(blank=True, null=True, upload_to='purchase_reject_bills/', verbose_name='Ảnh bill tại thời điểm từ chối')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reject_logs', to='finance.dailypurchase', verbose_name='Chi phí')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_reject_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người từ chối')),
            ],
            options={
                'verbose_name': 'Lịch sử từ chối chi phí',
                'verbose_name_plural': 'Lịch sử từ chối chi phí',
                'ordering': ['-rejected_at'],
            },
        ),
    ]
