# Generated by Django 6.0.4 on 2026-04-28 09:25

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_purchaserejectlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypurchase',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to=finance.models.upload_bill_image, verbose_name='Ảnh bill'),
        ),
        migrations.AlterField(
            model_name='purchaserejectlog',
            name='bill_image_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to=finance.models.upload_reject_bill_image, verbose_name='Ảnh bill tại thời điểm từ chối'),
        ),
    ]
