# Generated by Django 6.0.4 on 2026-04-30 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_dailypurchase_bill_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailypurchase',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Chi phí mua hàng ngày', 'verbose_name_plural': 'Chi phí mua hàng ngày'},
        ),
        migrations.AddField(
            model_name='dailypurchase',
            name='purchase_type',
            field=models.CharField(choices=[('main', 'Mua nguyên liệu chính'), ('extra', 'Mua bổ sung')], default='main', max_length=20, verbose_name='Phân loại'),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='date',
            field=models.DateField(verbose_name='Ngày'),
        ),
        migrations.CreateModel(
            name='PurchaseExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255, verbose_name='Nguyên liệu')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Số lượng')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Đơn vị')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='finance.dailypurchase', verbose_name='Phiếu mua bổ sung')),
            ],
            options={
                'verbose_name': 'Nguyên liệu mua bổ sung',
                'verbose_name_plural': 'Nguyên liệu mua bổ sung',
                'ordering': ['id'],
            },
        ),
    ]
