# Generated by Django 6.0.4 on 2026-04-24 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày đánh giá')),
                ('food_quality_score', models.PositiveSmallIntegerField(verbose_name='Chất lượng món ăn')),
                ('taste_score', models.PositiveSmallIntegerField(verbose_name='Khẩu vị')),
                ('freshness_score', models.PositiveSmallIntegerField(verbose_name='Độ nóng / độ tươi')),
                ('portion_score', models.PositiveSmallIntegerField(verbose_name='Khẩu phần')),
                ('hygiene_score', models.PositiveSmallIntegerField(verbose_name='Vệ sinh / trình bày')),
                ('overall_score', models.PositiveSmallIntegerField(verbose_name='Hài lòng chung')),
                ('comment', models.TextField(blank=True, verbose_name='Góp ý thêm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name': 'Đánh giá bữa ăn',
                'verbose_name_plural': 'Đánh giá bữa ăn',
                'ordering': ['-date', '-updated_at'],
                'unique_together': {('date', 'user')},
            },
        ),
    ]
