# Generated by Django 6.0.4 on 2026-05-08 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_alter_weeklymenudraft_unique_together_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealreview',
            name='food_quality_score',
        ),
        migrations.RemoveField(
            model_name='mealreview',
            name='freshness_score',
        ),
        migrations.RemoveField(
            model_name='mealreview',
            name='hygiene_score',
        ),
        migrations.RemoveField(
            model_name='mealreview',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='mealreview',
            name='portion_score',
        ),
        migrations.RemoveField(
            model_name='mealreview',
            name='taste_score',
        ),
        migrations.CreateModel(
            name='DishReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(choices=[('like', 'Thích'), ('dislike', 'Không thích')], max_length=10, verbose_name='Đánh giá')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='meals.dish')),
                ('meal_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_reviews', to='reviews.mealreview')),
            ],
            options={
                'verbose_name': 'Đánh giá món ăn',
                'verbose_name_plural': 'Đánh giá món ăn',
                'unique_together': {('meal_review', 'dish')},
            },
        ),
    ]
