# Generated by Django 6.0.4 on 2026-05-08 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_mealreview_food_quality_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealreview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mealreview',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Session Key ẩn danh'),
        ),
        migrations.AlterField(
            model_name='mealreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá'),
        ),
        migrations.AddConstraint(
            model_name='mealreview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('date', 'user'), name='unique_user_date_review'),
        ),
    ]
