# Generated by Django 6.0.4 on 2026-05-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_mealreview_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mattermost_post_id', models.CharField(max_length=64, unique=True, verbose_name='ID post trên NetChat')),
                ('channel_id', models.CharField(max_length=64)),
                ('sender_username', models.CharField(max_length=100, verbose_name='Username NetChat')),
                ('sender_full_name', models.CharField(blank=True, max_length=255, verbose_name='Họ tên')),
                ('employee_code', models.CharField(blank=True, help_text='Tự động lookup từ email trong UserProfile (để trống nếu không match)', max_length=50, verbose_name='Mã nhân viên')),
                ('message', models.TextField(verbose_name='Nội dung tin nhắn')),
                ('posted_at', models.DateTimeField(verbose_name='Thời điểm gửi (NetChat)')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm crawl về')),
            ],
            options={
                'verbose_name': 'Góp ý qua NetChat',
                'verbose_name_plural': 'Góp ý qua NetChat',
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['-posted_at'], name='reviews_fee_posted__9b7eec_idx')],
            },
        ),
    ]
