# Generated by Django 6.0.4 on 2026-05-14 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_delete_feedbackmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DishSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tên món đề xuất')),
                ('name_normalized', models.CharField(max_length=120, unique=True)),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Số lượt đề xuất')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_voted_at', models.DateTimeField(auto_now=True)),
                ('last_voted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đề xuất món ăn',
                'verbose_name_plural': 'Đề xuất món ăn',
                'ordering': ['-count', '-last_voted_at'],
            },
        ),
    ]
