# Generated by Django 6.0.4 on 2026-05-14 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_dishsuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishsuggestion',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Số voter'),
        ),
        migrations.CreateModel(
            name='DishSuggestionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.dishsuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote đề xuất món',
                'verbose_name_plural': 'Vote đề xuất món',
                'unique_together': {('suggestion', 'user')},
            },
        ),
    ]
