# Generated by Django 6.0.4 on 2026-04-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, verbose_name='Mã nhân viên')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Họ và tên')),
                ('date', models.DateField(verbose_name='Ngày đặt cơm')),
                ('meal_name', models.CharField(blank=True, max_length=100, verbose_name='Bữa ăn')),
                ('kitchen_name', models.CharField(blank=True, max_length=255, verbose_name='Tên bếp ăn')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số suất đặt')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Trạng thái')),
                ('source', models.CharField(default='excel', max_length=50, verbose_name='Nguồn dữ liệu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đăng kí suất ăn',
                'verbose_name_plural': 'Đăng kí suất ăn',
                'ordering': ['-date', 'employee_code'],
                'unique_together': {('employee_code', 'date', 'meal_name', 'kitchen_name')},
            },
        ),
    ]
