# Generated by Django 6.0.4 on 2026-05-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='Ngày đăng ký')),
                ('employee_code', models.CharField(max_length=50, verbose_name='Mã nhân viên')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Họ và tên')),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('failed', 'Thất bại')], max_length=20, verbose_name='Trạng thái')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Chi tiết lỗi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
            ],
            options={
                'verbose_name': 'Log gửi tin nhắn',
                'verbose_name_plural': 'Log gửi tin nhắn',
                'ordering': ['-created_at'],
            },
        ),
    ]
