# Generated by Django 6.0.4 on 2026-05-27 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_notificationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_employee_code', models.CharField(max_length=50, verbose_name='Mã NV chuyển')),
                ('from_full_name', models.CharField(blank=True, max_length=255, verbose_name='Tên người chuyển')),
                ('to_employee_code', models.CharField(max_length=50, verbose_name='Mã NV nhận')),
                ('to_full_name', models.CharField(blank=True, max_length=255, verbose_name='Tên người nhận')),
                ('meal_date', models.DateField(verbose_name='Ngày suất ăn')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('pending', 'Chờ áp dụng'), ('applied', 'Đã áp dụng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Lý do hủy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_transfers_from', to=settings.AUTH_USER_MODEL, verbose_name='Người chuyển')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_transfers_to', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Chuyển suất ăn',
                'verbose_name_plural': 'Chuyển suất ăn',
                'ordering': ['-created_at'],
            },
        ),
    ]
