# Generated by Django 6.0.4 on 2026-06-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_mealtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealregistration',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ghi chú'),
        ),
    ]
