# Generated by Django 6.0.4 on 2026-04-22 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPriceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật')], max_length=20, verbose_name='Hành động')),
                ('old_start_date', models.DateField(blank=True, null=True, verbose_name='Từ ngày cũ')),
                ('old_end_date', models.DateField(blank=True, null=True, verbose_name='Đến ngày cũ')),
                ('old_meal_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá cũ')),
                ('new_start_date', models.DateField(verbose_name='Từ ngày mới')),
                ('new_end_date', models.DateField(blank=True, null=True, verbose_name='Đến ngày mới')),
                ('new_meal_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá mới')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do thay đổi')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thay đổi')),
                ('meal_price_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='core.mealpricesetting', verbose_name='Cấu hình giá')),
            ],
            options={
                'verbose_name': 'Log thay đổi giá suất ăn',
                'verbose_name_plural': 'Log thay đổi giá suất ăn',
                'ordering': ['-changed_at'],
            },
        ),
    ]
